repos:
  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        language: system
        files: \.nix$

      - id: statix
        name: statix
        entry: statix check
        language: system
        files: \.nix$
        pass_filenames: false

      - id: deadnix
        name: deadnix
        entry: deadnix --fail
        language: system
        files: \.nix$
        pass_filenames: false

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        name: shellcheck (Google Shell Style Guide check)
        args: ["--severity=warning"]

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      - id: shfmt
        name: shfmt (Google Shell Formatting)
        args: ["-i", "2", "-ci", "-bn"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1024]

