schema = 3

[mod]
  [mod.'github.com/beorn7/perks']
    version = 'v1.0.1'
    hash = 'sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4='

  [mod.'github.com/cespare/xxhash/v2']
    version = 'v2.3.0'
    hash = 'sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY='

  [mod.'github.com/coreos/go-systemd/v22']
    version = 'v22.5.0'
    hash = 'sha256-E2zXikbmIQImghstLUWuey1YgA0Folu3F+fi5k4hCxA='

  [mod.'github.com/creack/pty']
    version = 'v1.1.24'
    hash = 'sha256-6oSurN/ZYr/KHxKKU6Qbw9w8CDKmPa8yL00pZ24H0AM='

  [mod.'github.com/godbus/dbus/v5']
    version = 'v5.1.0'
    hash = 'sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/gorilla/websocket']
    version = 'v1.5.3'
    hash = 'sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0='

  [mod.'github.com/klauspost/compress']
    version = 'v1.17.9'
    hash = 'sha256-FxHk4OuwsbiH1OLI+Q0oA4KpcOB786sEfik0G+GNoow='

  [mod.'github.com/munnerz/goautoneg']
    version = 'v0.0.0-20191010083416-a7dc8b61c822'
    hash = 'sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q='

  [mod.'github.com/prometheus/client_golang']
    version = 'v1.20.5'
    hash = 'sha256-RbDZTBH+j2ZNLbHSMFxW0j8UStvkwc4IHTz3My9w4qo='

  [mod.'github.com/prometheus/client_model']
    version = 'v0.6.1'
    hash = 'sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw='

  [mod.'github.com/prometheus/common']
    version = 'v0.55.0'
    hash = 'sha256-qzvCnc+hnAB5dq2MYy8GlPxgyNnyn9kFVlN2CXZe9T0='

  [mod.'github.com/prometheus/procfs']
    version = 'v0.15.1'
    hash = 'sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw='

  [mod.'golang.org/x/sys']
    version = 'v0.22.0'
    hash = 'sha256-RbG0XaXGGlErCsl2agvUxMnrkRwdbJLmriYT1H24FwA='

  [mod.'google.golang.org/protobuf']
    version = 'v1.34.2'
    hash = 'sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0='

  [mod.'pgregory.net/rapid']
    version = 'v1.1.0'
    hash = 'sha256-sVQY9EQ9Y5blYyVYfaOa+y12e+399OqdHiEY3BaDnqo='
