import type { ITheme } from "@xterm/xterm";

export interface TerminalThemeDefinition {
    id: string;
    name: string;
    description: string;
    isAdaptive?: boolean;
    theme: ITheme;
}

export const ANTHROPIC_DARK_THEME: ITheme = {
    background: "#141413",
    foreground: "#ECEBE6",
    cursor: "#D97757",
    cursorAccent: "#141413",
    selectionBackground: "#3D3835",
    selectionForeground: "#FFFFFF",
    black: "#242320",
    red: "#F87171",
    green: "#4ADE80",
    yellow: "#FBBF24",
    blue: "#60A5FA",
    magenta: "#C084FC",
    cyan: "#38BDF8",
    white: "#D1D0C7",
    brightBlack: "#5E5D59",
    brightRed: "#FCA5A5",
    brightGreen: "#86EFAC",
    brightYellow: "#FDE047",
    brightBlue: "#93C5FD",
    brightMagenta: "#E9D5FF",
    brightCyan: "#7DD3FC",
    brightWhite: "#FAF9F5",
};

export const ANTHROPIC_LIGHT_THEME: ITheme = {
    background: "#FAF9F5",
    foreground: "#141413",
    cursor: "#D97757",
    cursorAccent: "#FAF9F5",
    selectionBackground: "#E6E2D8",
    selectionForeground: "#141413",
    black: "#3D3C38",
    red: "#DC2626",
    green: "#16A34A",
    yellow: "#D97706",
    blue: "#2563EB",
    magenta: "#9333EA",
    cyan: "#0891B2",
    white: "#87867F",
    brightBlack: "#6B6960",
    brightRed: "#EF4444",
    brightGreen: "#22C55E",
    brightYellow: "#F59E0B",
    brightBlue: "#3B82F6",
    brightMagenta: "#A855F7",
    brightCyan: "#06B6D4",
    brightWhite: "#141413",
};

export const TERMINAL_THEMES: Record<string, TerminalThemeDefinition> = {
    adaptive: {
        id: "adaptive",
        name: "Adaptive (System & Theme Sync)",
        description: "Automatically switches between Anthropic Ivory and Onyx based on UI mode",
        isAdaptive: true,
        theme: ANTHROPIC_DARK_THEME,
    },
    anthropicDark: {
        id: "anthropicDark",
        name: "Anthropic Dark (Onyx)",
        description: "Warm onyx slate with signature terracotta prompt highlights",
        theme: ANTHROPIC_DARK_THEME,
    },
    anthropicLight: {
        id: "anthropicLight",
        name: "Anthropic Light (Ivory)",
        description: "Editorial ivory paper with crisp high-contrast dark typography",
        theme: ANTHROPIC_LIGHT_THEME,
    },
    nixos: {
        id: "nixos",
        name: "NixOS Blue",
        description: "Official NixOS brand inspired deep blue and cyan palette",
        theme: {
            background: "#0d1117",
            foreground: "#c9d1d9",
            cursor: "#5277c3",
            cursorAccent: "#0d1117",
            selectionBackground: "#264f78",
            selectionForeground: "#ffffff",
            black: "#161b22",
            red: "#ff7b72",
            green: "#7ee787",
            yellow: "#d29922",
            blue: "#5277c3",
            magenta: "#bc8cff",
            cyan: "#7ebae4",
            white: "#f0f6fc",
            brightBlack: "#484f58",
            brightRed: "#ffa198",
            brightGreen: "#56d364",
            brightYellow: "#e3b341",
            brightBlue: "#79c0ff",
            brightMagenta: "#d2a8ff",
            brightCyan: "#a5d6ff",
            brightWhite: "#ffffff",
        },
    },
    catppuccin: {
        id: "catppuccin",
        name: "Catppuccin Mocha",
        description: "Soothing pastel dark theme with mauve and lavender accents",
        theme: {
            background: "#1e1e2e",
            foreground: "#cdd6f4",
            cursor: "#cba6f7",
            cursorAccent: "#1e1e2e",
            selectionBackground: "#45475a",
            selectionForeground: "#cdd6f4",
            black: "#45475a",
            red: "#f38ba8",
            green: "#a6e3a1",
            yellow: "#f9e2af",
            blue: "#89b4fa",
            magenta: "#f5c2e7",
            cyan: "#94e2d5",
            white: "#bac2de",
            brightBlack: "#585b70",
            brightRed: "#f38ba8",
            brightGreen: "#a6e3a1",
            brightYellow: "#f9e2af",
            brightBlue: "#89b4fa",
            brightMagenta: "#f5c2e7",
            brightCyan: "#94e2d5",
            brightWhite: "#a6adc8",
        },
    },
    tokyoNight: {
        id: "tokyoNight",
        name: "Tokyo Night",
        description: "Clean dark theme celebrating the neon lights of Tokyo",
        theme: {
            background: "#1a1b26",
            foreground: "#a9b1d6",
            cursor: "#7aa2f7",
            cursorAccent: "#1a1b26",
            selectionBackground: "#283457",
            selectionForeground: "#c0caf5",
            black: "#32344a",
            red: "#f7768e",
            green: "#9ece6a",
            yellow: "#e0af68",
            blue: "#7aa2f7",
            magenta: "#bb9af7",
            cyan: "#7dcfff",
            white: "#787c99",
            brightBlack: "#444b6a",
            brightRed: "#ff7a93",
            brightGreen: "#b9f27c",
            brightYellow: "#ff9e64",
            brightBlue: "#7da6ff",
            brightMagenta: "#bb9af7",
            brightCyan: "#0db9d7",
            brightWhite: "#acb0d0",
        },
    },
    nord: {
        id: "nord",
        name: "Nord Frost",
        description: "Arctic, north-bluish clean and elegant color palette",
        theme: {
            background: "#2e3440",
            foreground: "#d8dee9",
            cursor: "#88c0d0",
            cursorAccent: "#2e3440",
            selectionBackground: "#434c5e",
            selectionForeground: "#eceff4",
            black: "#3b4252",
            red: "#bf616a",
            green: "#a3be8c",
            yellow: "#ebcb8b",
            blue: "#81a1c1",
            magenta: "#b48ead",
            cyan: "#88c0d0",
            white: "#e5e9f0",
            brightBlack: "#4c566a",
            brightRed: "#d08770",
            brightGreen: "#a3be8c",
            brightYellow: "#ebcb8b",
            brightBlue: "#81a1c1",
            brightMagenta: "#b48ead",
            brightCyan: "#8fbcbb",
            brightWhite: "#eceff4",
        },
    },
    gruvbox: {
        id: "gruvbox",
        name: "Gruvbox Dark",
        description: "Retro groove warm dark palette with earthy colors",
        theme: {
            background: "#282828",
            foreground: "#ebdbb2",
            cursor: "#fe8019",
            cursorAccent: "#282828",
            selectionBackground: "#504945",
            selectionForeground: "#fbf1c7",
            black: "#282828",
            red: "#cc241d",
            green: "#98971a",
            yellow: "#d79921",
            blue: "#458588",
            magenta: "#b16286",
            cyan: "#689d6a",
            white: "#a89984",
            brightBlack: "#928374",
            brightRed: "#fb4934",
            brightGreen: "#b8bb26",
            brightYellow: "#fabd2f",
            brightBlue: "#83a598",
            brightMagenta: "#d3869b",
            brightCyan: "#8ec07c",
            brightWhite: "#ebdbb2",
        },
    },
    oled: {
        id: "oled",
        name: "OLED Pitch Black",
        description: "Pure true black #000000 background with high-contrast neon highlights",
        theme: {
            background: "#000000",
            foreground: "#f0f0f0",
            cursor: "#00ff9f",
            cursorAccent: "#000000",
            selectionBackground: "#1e3a2f",
            selectionForeground: "#00ff9f",
            black: "#1a1a1a",
            red: "#ff5252",
            green: "#00ff9f",
            yellow: "#ffd600",
            blue: "#00b0ff",
            magenta: "#e040fb",
            cyan: "#18ffff",
            white: "#e0e0e0",
            brightBlack: "#424242",
            brightRed: "#ff8a80",
            brightGreen: "#b9f6ca",
            brightYellow: "#ffff8d",
            brightBlue: "#80d8ff",
            brightMagenta: "#ea80fc",
            brightCyan: "#84ffff",
            brightWhite: "#ffffff",
        },
    },
};

/**
 * Resolves the active terminal theme, considering light/dark mode and adaptive settings.
 */
export function resolveTerminalTheme(themeId: string, isLightMode: boolean): ITheme {
    if (themeId === "adaptive" || !themeId) {
        return isLightMode ? ANTHROPIC_LIGHT_THEME : ANTHROPIC_DARK_THEME;
    }
    const def = TERMINAL_THEMES[themeId];
    if (def) {
        return def.theme;
    }
    return isLightMode ? ANTHROPIC_LIGHT_THEME : ANTHROPIC_DARK_THEME;
}
