import type { ITheme } from "@xterm/xterm";

export interface TerminalThemeDefinition {
    id: string;
    name: string;
    description: string;
    theme: ITheme;
}

export const TERMINAL_THEMES: Record<string, TerminalThemeDefinition> = {
    nixos: {
        id: "nixos",
        name: "NixOS Blue (Default)",
        description: "Official NixOS brand inspired deep blue and cyan palette",
        theme: {
            background: "#0d1117",
            foreground: "#c9d1d9",
            cursor: "#5277c3",
            cursorAccent: "#0d1117",
            selectionBackground: "#264f78",
            selectionForeground: "#ffffff",
            black: "#161b22",
            red: "#ff7b72",
            green: "#7ee787",
            yellow: "#d29922",
            blue: "#5277c3",
            magenta: "#bc8cff",
            cyan: "#7ebae4",
            white: "#f0f6fc",
            brightBlack: "#484f58",
            brightRed: "#ffa198",
            brightGreen: "#56d364",
            brightYellow: "#e3b341",
            brightBlue: "#79c0ff",
            brightMagenta: "#d2a8ff",
            brightCyan: "#a5d6ff",
            brightWhite: "#ffffff",
        },
    },
    catppuccin: {
        id: "catppuccin",
        name: "Catppuccin Mocha",
        description: "Soothing pastel dark theme with mauve and lavender accents",
        theme: {
            background: "#1e1e2e",
            foreground: "#cdd6f4",
            cursor: "#cba6f7",
            cursorAccent: "#1e1e2e",
            selectionBackground: "#45475a",
            selectionForeground: "#cdd6f4",
            black: "#45475a",
            red: "#f38ba8",
            green: "#a6e3a1",
            yellow: "#f9e2af",
            blue: "#89b4fa",
            magenta: "#f5c2e7",
            cyan: "#94e2d5",
            white: "#bac2de",
            brightBlack: "#585b70",
            brightRed: "#f38ba8",
            brightGreen: "#a6e3a1",
            brightYellow: "#f9e2af",
            brightBlue: "#89b4fa",
            brightMagenta: "#f5c2e7",
            brightCyan: "#94e2d5",
            brightWhite: "#a6adc8",
        },
    },
    tokyoNight: {
        id: "tokyoNight",
        name: "Tokyo Night",
        description: "Clean dark theme celebrating the neon lights of Tokyo",
        theme: {
            background: "#1a1b26",
            foreground: "#a9b1d6",
            cursor: "#7aa2f7",
            cursorAccent: "#1a1b26",
            selectionBackground: "#283457",
            selectionForeground: "#c0caf5",
            black: "#32344a",
            red: "#f7768e",
            green: "#9ece6a",
            yellow: "#e0af68",
            blue: "#7aa2f7",
            magenta: "#bb9af7",
            cyan: "#7dcfff",
            white: "#787c99",
            brightBlack: "#444b6a",
            brightRed: "#ff7a93",
            brightGreen: "#b9f27c",
            brightYellow: "#ff9e64",
            brightBlue: "#7da6ff",
            brightMagenta: "#bb9af7",
            brightCyan: "#0db9d7",
            brightWhite: "#acb0d0",
        },
    },
    nord: {
        id: "nord",
        name: "Nord Frost",
        description: "Arctic, north-bluish clean and elegant color palette",
        theme: {
            background: "#2e3440",
            foreground: "#d8dee9",
            cursor: "#88c0d0",
            cursorAccent: "#2e3440",
            selectionBackground: "#434c5e",
            selectionForeground: "#eceff4",
            black: "#3b4252",
            red: "#bf616a",
            green: "#a3be8c",
            yellow: "#ebcb8b",
            blue: "#81a1c1",
            magenta: "#b48ead",
            cyan: "#88c0d0",
            white: "#e5e9f0",
            brightBlack: "#4c566a",
            brightRed: "#d08770",
            brightGreen: "#a3be8c",
            brightYellow: "#ebcb8b",
            brightBlue: "#81a1c1",
            brightMagenta: "#b48ead",
            brightCyan: "#8fbcbb",
            brightWhite: "#eceff4",
        },
    },
    gruvbox: {
        id: "gruvbox",
        name: "Gruvbox Dark",
        description: "Retro groove warm dark palette with earthy colors",
        theme: {
            background: "#282828",
            foreground: "#ebdbb2",
            cursor: "#fe8019",
            cursorAccent: "#282828",
            selectionBackground: "#504945",
            selectionForeground: "#fbf1c7",
            black: "#282828",
            red: "#cc241d",
            green: "#98971a",
            yellow: "#d79921",
            blue: "#458588",
            magenta: "#b16286",
            cyan: "#689d6a",
            white: "#a89984",
            brightBlack: "#928374",
            brightRed: "#fb4934",
            brightGreen: "#b8bb26",
            brightYellow: "#fabd2f",
            brightBlue: "#83a598",
            brightMagenta: "#d3869b",
            brightCyan: "#8ec07c",
            brightWhite: "#ebdbb2",
        },
    },
    oled: {
        id: "oled",
        name: "OLED Pitch Black",
        description: "Pure true black #000000 background with high-contrast neon highlights",
        theme: {
            background: "#000000",
            foreground: "#f0f0f0",
            cursor: "#00ff9f",
            cursorAccent: "#000000",
            selectionBackground: "#1e3a2f",
            selectionForeground: "#00ff9f",
            black: "#1a1a1a",
            red: "#ff5252",
            green: "#00ff9f",
            yellow: "#ffd600",
            blue: "#00b0ff",
            magenta: "#e040fb",
            cyan: "#18ffff",
            white: "#e0e0e0",
            brightBlack: "#424242",
            brightRed: "#ff8a80",
            brightGreen: "#b9f6ca",
            brightYellow: "#ffff8d",
            brightBlue: "#80d8ff",
            brightMagenta: "#ea80fc",
            brightCyan: "#84ffff",
            brightWhite: "#ffffff",
        },
    },
};
