# Host: backup — restic SFTP target node
{
  user,
  ...
}:
{
  networking.hostName = "backup";
  system.stateVersion = "25.05";

  # SSH access for the backup node. mkServer sets isServer = true so
  # infrastructure/security/default.nix already enables and hardens sshd.
  # Only the authorised keys need to be declared here.
  l7v.identity.sshKeys = [
    # TODO: add restic client public key (generated by bootstrap.sh on source hosts)
    # "ssh-ed25519 AAAA... restic@l7v"
  ];

  # Restic repository directory on /srv/backup — mounted from hardware.nix.
  # The directory and permissions are created at activation time.
  systemd.tmpfiles.rules = [
    "d /srv/backup       0750 ${user} users -"
    "d /srv/backup/restic 0750 ${user} users -"
  ];
}
