package apps

// Predefined catalog of enterprise services and applications in the NixOS dotfiles ecosystem.
var defaultCatalog = []Application{
	// ─── 1. CORE SYSTEM SERVICES ──────────────────────────────────────────
	{
		ID:          "forgejo",
		Name:        "Forgejo Git Forge",
		Description: "Self-hosted lightweight Git repository & collaboration platform",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "forgejo.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "https", URL: "https://git.l7v.dev", Port: 3000, Internal: false},
			{Type: "http", URL: "http://127.0.0.1:3000", Port: 3000, Internal: true},
		},
		Dependencies: []string{"postgresql.service", "nginx.service"},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/services/forgejo/default.nix",
			PackageName: "forgejo",
			FlakeInput:  "nixpkgs",
			SecretKeys:  []string{"forgejo/admin_password"},
		},
		Tags: []string{"git", "vcs", "ci-cd", "core"},
	},
	{
		ID:          "vaultwarden",
		Name:        "Vaultwarden",
		Description: "Lightweight Bitwarden-compatible password and secrets manager",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "vaultwarden.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "https", URL: "https://vault.l7v.dev", Port: 8222, Internal: false},
			{Type: "http", URL: "http://127.0.0.1:8222", Port: 8222, Internal: true},
		},
		Dependencies: []string{"postgresql.service", "nginx.service"},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/services/vaultwarden/default.nix",
			PackageName: "vaultwarden",
			FlakeInput:  "nixpkgs",
			SecretKeys:  []string{"vaultwarden/env"},
		},
		Tags: []string{"security", "passwords", "sops", "core"},
	},
	{
		ID:          "grafana",
		Name:        "Grafana Dashboards",
		Description: "Observability, infrastructure telemetry & log visualizer",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "grafana.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "https", URL: "https://grafana.l7v.dev", Port: 3001, Internal: false},
			{Type: "http", URL: "http://127.0.0.1:3001", Port: 3001, Internal: true},
		},
		Dependencies: []string{"prometheus.service", "loki.service"},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/services/grafana/default.nix",
			PackageName: "grafana",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"metrics", "logs", "monitoring", "telemetry"},
	},
	{
		ID:          "prometheus",
		Name:        "Prometheus Server",
		Description: "Time-series metrics scraping engine & alerting database",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "prometheus.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "http", URL: "http://127.0.0.1:9090", Port: 9090, Internal: true},
		},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/metrics/prometheus.nix",
			PackageName: "prometheus",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"metrics", "scraper", "telemetry"},
	},
	{
		ID:          "loki",
		Name:        "Loki Log Aggregator",
		Description: "High-efficiency log aggregation system for Promtail / Journald",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "loki.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "http", URL: "http://127.0.0.1:3100", Port: 3100, Internal: true},
		},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/logging/loki.nix",
			PackageName: "loki",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"logging", "promtail", "telemetry"},
	},
	{
		ID:          "postgresql",
		Name:        "PostgreSQL Relational DB",
		Description: "Enterprise SQL database for Forgejo, Vaultwarden, Matrix and services",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "postgresql.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "tcp", URL: "localhost:5432", Port: 5432, Internal: true},
			{Type: "unix", URL: "/run/postgresql", Internal: true},
		},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/database/postgresql.nix",
			PackageName: "postgresql",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"database", "sql", "storage", "core"},
	},
	{
		ID:          "conduit",
		Name:        "Conduit Matrix Server",
		Description: "Lightweight, ultra-fast federated Matrix messaging homeserver",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "conduit.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "https", URL: "https://matrix.l7v.dev", Port: 6167, Internal: false},
			{Type: "http", URL: "http://127.0.0.1:6167", Port: 6167, Internal: true},
		},
		Dependencies: []string{"nginx.service"},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/messaging/conduit.nix",
			PackageName: "matrix-conduit",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"matrix", "messaging", "chat"},
	},
	{
		ID:          "nginx",
		Name:        "Nginx Reverse Proxy",
		Description: "Edge ingress proxy with automated ACME / Let's Encrypt TLS termination",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "nginx.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "http", URL: "http://0.0.0.0:80", Port: 80, Internal: false},
			{Type: "https", URL: "https://0.0.0.0:443", Port: 443, Internal: false},
		},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/reverse-proxy/nginx.nix",
			PackageName: "nginx",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"proxy", "ingress", "ssl", "tls"},
	},
	{
		ID:          "atticd",
		Name:        "Attic Nix Binary Cache",
		Description: "Multi-tenant Nix binary cache server for fast flake builds",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "atticd.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "http", URL: "http://127.0.0.1:8080", Port: 8080, Internal: true},
		},
		Dependencies: []string{"postgresql.service"},
		Provenance: NixProvenance{
			DeclaredIn:  "modules/services/attic/default.nix",
			PackageName: "attic-server",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"nix", "cache", "builds"},
	},
	{
		ID:          "restic-backup",
		Name:        "Restic Backup Engine",
		Description: "Automated snapshot backup service to encrypted remote storage",
		Category:    CategoryCoreService,
		Status:      StatusStopped,
		SystemdUnit: "restic-backups-system.service",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/backup/restic.nix",
			PackageName: "restic",
			FlakeInput:  "nixpkgs",
			SecretKeys:  []string{"backup/restic_password"},
		},
		Tags: []string{"backup", "security", "snapshots"},
	},
	{
		ID:          "panel-agent",
		Name:        "L7V Panel Agent",
		Description: "Systemd socket-activated D-Bus REST/SSE control plane daemon",
		Category:    CategoryCoreService,
		Status:      StatusRunning,
		SystemdUnit: "panel-agent.service",
		SandboxTier: SandboxTierNone,
		Endpoints: []AppEndpoint{
			{Type: "unix", URL: "/run/panel-agent/panel-agent.sock", Internal: true},
			{Type: "http", URL: "http://127.0.0.1:8080", Port: 8080, Internal: true},
		},
		Provenance: NixProvenance{
			DeclaredIn:  "panel/nix/module.nix",
			PackageName: "panel-agent",
			FlakeInput:  "local",
		},
		Tags: []string{"panel", "control-plane", "agent"},
	},

	// ─── 2. AI AGENTS & LLM DEV TOOLS ─────────────────────────────────────
	{
		ID:          "claudebox",
		Name:        "Claudebox Runner",
		Description: "Sandboxed Anthropic Claude Code runner with bubblewrap isolation",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "claudebox",
		SandboxTier: SandboxTierClaudebox,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "claudebox",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"ai", "agent", "claude", "sandbox"},
	},
	{
		ID:          "claude-code",
		Name:        "Claude Code CLI",
		Description: "Anthropic Claude Code autonomous terminal coding agent",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "claude",
		SandboxTier: SandboxTierClaudebox,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "claude-code",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"ai", "agent", "claude", "terminal"},
	},
	{
		ID:          "aider-chat",
		Name:        "Aider Pair Programmer",
		Description: "Multi-model AI pair programmer in your terminal with git integration",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "aider",
		SandboxTier: SandboxTierClaudebox,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "aider-chat",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"ai", "pair-programming", "git"},
	},
	{
		ID:          "cc-sdd",
		Name:        "CC-SDD Spec Harness",
		Description: "Spec-Driven Development orchestration harness for autonomous agents",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "cc-sdd",
		SandboxTier: SandboxTierWorktree,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "cc-sdd",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"ai", "sdd", "spec", "workflow"},
	},
	{
		ID:          "vibe-kanban",
		Name:        "Vibe Kanban Board",
		Description: "Multi-agent autonomous task orchestration kanban dashboard",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "vibe-kanban",
		SandboxTier: SandboxTierClaudebox,
		Endpoints: []AppEndpoint{
			{Type: "http", URL: "http://localhost:3333", Port: 3333, Internal: true},
		},
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "vibe-kanban",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"ai", "kanban", "tasks", "web"},
	},
	{
		ID:          "goose-cli",
		Name:        "Goose Autonomous Agent",
		Description: "Block/Square extensible autonomous on-machine coding agent",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "goose",
		SandboxTier: SandboxTierClaudebox,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "goose-cli",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"ai", "agent", "goose", "square"},
	},
	{
		ID:          "codex",
		Name:        "OpenAI Codex CLI",
		Description: "Command-line assistant powered by OpenAI models",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "codex",
		SandboxTier: SandboxTierClaudebox,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "codex",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"ai", "openai", "codex"},
	},
	{
		ID:          "gemini-cli",
		Name:        "Google Gemini CLI",
		Description: "High-performance Google Gemini multimodal terminal interface",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "gemini",
		SandboxTier: SandboxTierClaudebox,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "gemini-cli",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"ai", "google", "gemini"},
	},
	{
		ID:          "opencode",
		Name:        "OpenCode Terminal Agent",
		Description: "Multi-provider terminal AI agent supporting local and cloud LLMs",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "opencode",
		SandboxTier: SandboxTierClaudebox,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "opencode",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"ai", "llm", "terminal"},
	},
	{
		ID:          "openskills",
		Name:        "OpenSkills Universal Loader",
		Description: "Standardized agent skills loader across multiple AI frameworks",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "openskills",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "openskills",
			FlakeInput:  "llm-agents",
		},
		Tags: []string{"skills", "plugins", "tooling"},
	},
	{
		ID:          "kiro-cli",
		Name:        "Kiro AI Agent CLI",
		Description: "Kiro autonomous coding assistant CLI interface",
		Category:    CategoryAIAgent,
		Status:      StatusStandby,
		BinaryName:  "kiro-cli",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "home/profiles/ai-tools.nix",
			PackageName: "kiro-cli",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"ai", "kiro", "agent"},
	},

	// ─── 3. MICROVM & SANDBOX WORKLOADS ──────────────────────────────────
	{
		ID:          "microvm-coding-agent",
		Name:        "MicroVM Coding Sandbox",
		Description: "Ephemeral Linux MicroVM for high-risk untrusted code execution",
		Category:    CategoryMicroVM,
		Status:      StatusStopped,
		SystemdUnit: "microvm@coding-agent.service",
		SandboxTier: SandboxTierMicroVM,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/virtualisation/microvm.nix",
			PackageName: "microvm.nix",
			FlakeInput:  "microvm",
		},
		Tags: []string{"microvm", "hypervisor", "isolation", "tier2"},
	},
	{
		ID:          "libvirtd",
		Name:        "Libvirt Virtualisation Daemon",
		Description: "KVM/QEMU hypervisor management service for virtual machines",
		Category:    CategoryMicroVM,
		Status:      StatusStopped,
		SystemdUnit: "libvirtd.service",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/capabilities/virtualisation/libvirt.nix",
			PackageName: "libvirt",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"kvm", "qemu", "vms"},
	},

	// ─── 4. DEVELOPER TOOLS & PLATFORM ────────────────────────────────────
	{
		ID:          "qoder",
		Name:        "Qoder AI-Native IDE",
		Description: "Custom packaged AI-accelerated code editor environment",
		Category:    CategoryDevTool,
		Status:      StatusStandby,
		BinaryName:  "qoder",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "pkgs/qoder/default.nix",
			PackageName: "qoder",
			FlakeInput:  "local",
		},
		Tags: []string{"ide", "editor", "developer"},
	},
	{
		ID:          "colmena",
		Name:        "Colmena Deployer",
		Description: "Declarative NixOS host fleet deployment and rollback engine",
		Category:    CategoryDevTool,
		Status:      StatusStandby,
		BinaryName:  "colmena",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/platform/deploy/default.nix",
			PackageName: "colmena",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"deploy", "nixos", "infra"},
	},
	{
		ID:          "buildkite-agent",
		Name:        "Buildkite CI Agent",
		Description: "Self-hosted continuous integration and build runner daemon",
		Category:    CategoryDevTool,
		Status:      StatusStopped,
		SystemdUnit: "buildkite-agent.service",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/platform/ci/default.nix",
			PackageName: "buildkite-agent",
			FlakeInput:  "nixpkgs",
			SecretKeys:  []string{"buildkite/token"},
		},
		Tags: []string{"ci", "build", "pipeline"},
	},

	// ─── 5. DESKTOP & SYSTEM CAPABILITIES ─────────────────────────────────
	{
		ID:          "pipewire",
		Name:        "PipeWire Audio Server",
		Description: "Low-latency pro-audio and video processing pipeline daemon",
		Category:    CategoryDesktopCap,
		Status:      StatusRunning,
		SystemdUnit: "pipewire.service",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/experience/capabilities/audio.nix",
			PackageName: "pipewire",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"audio", "media", "system"},
	},
	{
		ID:          "networkmanager",
		Name:        "NetworkManager",
		Description: "System network connectivity and wireless interface coordinator",
		Category:    CategoryDesktopCap,
		Status:      StatusRunning,
		SystemdUnit: "NetworkManager.service",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/infrastructure/network/default.nix",
			PackageName: "networkmanager",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"network", "wifi", "ethernet"},
	},
	{
		ID:          "tailscale",
		Name:        "Tailscale VPN Mesh",
		Description: "Zero-trust WireGuard mesh overlay network daemon",
		Category:    CategoryDesktopCap,
		Status:      StatusStopped,
		SystemdUnit: "tailscaled.service",
		SandboxTier: SandboxTierNone,
		Provenance: NixProvenance{
			DeclaredIn:  "modules/infrastructure/security/default.nix",
			PackageName: "tailscale",
			FlakeInput:  "nixpkgs",
		},
		Tags: []string{"vpn", "wireguard", "mesh", "security"},
	},
}
