# Secrets capability: sops-nix + age key management.
#
# The age private key lives at /etc/age/key (generated by scripts/bootstrap.sh).
# The matching public key must be registered in secrets/sops/.sops.yaml before
# running `sops updatekeys secrets/sops/secrets.yaml`.
{
  lib,
  config,
  pkgs,
  ...
}:
{
  options.l7v.secrets = {
    enable = lib.mkEnableOption "sops-nix secrets capability";

    hosts = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = { };
      description = "Mapping of hostname to age public key for cross-host secret distribution.";
      example = {
        server = "age1abc...";
        builder = "age1def...";
        backup = "age1ghi...";
      };
    };
  };

  config = lib.mkIf config.l7v.secrets.enable {
    sops = {
      defaultSopsFile = ../../secrets/sops/secrets.yaml;
      age = {
        keyFile = "/etc/age/key";
        generateKey = false;
      };
    };

    # Ensure the age key directory exists before sops-nix tries to read the key.
    system.activationScripts.ageKeyDir = ''
      mkdir -p /etc/age
      chmod 700 /etc/age
    '';

    environment.systemPackages = with pkgs; [
      age
      sops
      ssh-to-age # convert SSH Ed25519 keys to age format
    ];
  };
}
